#!/usr/bin/env python3
"""
pokered_assets/maps/*.png + *.json → src/data/map_data.h

bake_assets.py 가 .blk/.bst/.asm 을 PNG+JSON 으로 미리 변환해놓아서
이 스크립트는 PNG 픽셀 색을 char 로 디코드하고 JSON 메타를 합쳐 헤더로 출력한다.
"""
import os, sys, json
from PIL import Image

ROOT   = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.normpath(os.path.join(ROOT, "..", "pokered_assets"))
OUT    = os.path.normpath(os.path.join(ROOT, "..", "src", "data", "map_data.h"))

# bake_assets.py 와 동일 매핑 (RGB → char)
CHAR_TO_COLOR = {
    ' ': (120, 200,  80), '.': (210, 180, 110), ',': (160, 220, 110),
    ';': ( 40, 130,  40), '#': (110, 110, 110), '~': ( 50, 110, 200),
    'D': (220,  80,  80), 's': (240, 220, 100), 'T': ( 25,  80,  30),
    'N': (255,   0, 255), 'H': (180, 140,  80), 'L': (220,  60,  60),
    'C': (220,  90,  90), 'G': (220, 100, 100), 'M': (220, 110, 110),
    'B': (140, 140, 140), 'P': (200, 200, 200),
}
COLOR_TO_CHAR = {v: k for k, v in CHAR_TO_COLOR.items()}

INTERIOR_TILESETS = {"reds_house", "reds_house_1", "reds_house_2", "house",
                     "lab", "gym", "pokecenter", "mart", "lobby", "mansion"}

# 맵 정의 — bake 결과 PNG/JSON 파일명과 cpp_id, 한국어명 매핑
MAPS = [
    ("MAP_PALLET",       "Pallet Town",     "팔레트시티",     "PalletTown"),
    ("MAP_ROUTE1",       "Route 1",         "1번도로",         "Route1"),
    ("MAP_VIRIDIAN",     "Viridian City",   "상록시티",       "ViridianCity"),
    ("MAP_ROUTE2",       "Route 2",         "2번도로",         "Route2"),
    ("MAP_VIR_FOREST",   "Viridian Forest", "상록숲",         "ViridianForest"),
    ("MAP_PEWTER",       "Pewter City",     "회색시티",       "PewterCity"),
    ("MAP_OAK_LAB",      "Oak's Lab",       "오박사 연구소",   "OaksLab"),
    ("MAP_PLAYER_HOUSE", "Player's House",  "주인공의 집",    "RedsHouse1F"),
    ("MAP_PEWTER_GYM",   "Pewter Gym",      "회색시티 체육관", "PewterGym"),
]

# 맵 이름 → cpp_id 매핑 (warp dest 변환용)
NAME_TO_CPP = {
    "PALLET_TOWN":      "MAP_PALLET",
    "ROUTE_1":          "MAP_ROUTE1",
    "VIRIDIAN_CITY":    "MAP_VIRIDIAN",
    "ROUTE_2":          "MAP_ROUTE2",
    "VIRIDIAN_FOREST":  "MAP_VIR_FOREST",
    "PEWTER_CITY":      "MAP_PEWTER",
    "PEWTER_GYM":       "MAP_PEWTER_GYM",
    "OAKS_LAB":         "MAP_OAK_LAB",
    "REDS_HOUSE_1F":    "MAP_PLAYER_HOUSE",
    "REDS_HOUSE_2F":    "MAP_PLAYER_HOUSE2",
    "BLUES_HOUSE":      "MAP_RIVAL_HOUSE",
    "LAST_MAP":         "MAP_PALLET",
}

def map_dest(name):
    return NAME_TO_CPP.get(name, f"-1 /*{name}*/")

def load_map_png(blk_name):
    """PNG 픽셀 색을 char 로 디코드해 row 리스트 반환."""
    p = os.path.join(ASSETS, "maps", f"{blk_name}.png")
    img = Image.open(p).convert("RGB")
    w, h = img.size
    rows = []
    for y in range(h):
        row = ""
        for x in range(w):
            color = img.getpixel((x, y))
            row += COLOR_TO_CHAR.get(color, ' ')
        rows.append(row)
    return rows, w, h

def load_map_json(blk_name):
    p = os.path.join(ASSETS, "maps", f"{blk_name}.json")
    with open(p, "r", encoding="utf-8") as f:
        return json.load(f)

def escape_row(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')

def generate():
    print("맵 PNG/JSON → map_data.h\n")
    out = []
    out.append("// SEMI-AUTO-GENERATED by tools/gen_maps.py")
    out.append("// 골격(타일/워프)은 자동 생성, NPC/대사/트리거/추가 맵은 손편집 영역.")
    out.append("// 재생성 시 손편집된 NPC 데이터(엄마/Daisy/오박사 등)와 MAP_RIVAL_HOUSE 정의가 사라집니다.")
    out.append("// 재생성 후엔 git diff로 손편집 영역 복원 필요.")
    out.append("#pragma once")
    out.append('#include "sprites.h"  // NPC_SPR_* enum 사용')
    out.append("")
    out.append("// 타일 종류")
    out.append("// ' '=땅 '.'=길 ','=짧은풀 ';'=긴풀 '#'=벽 '~'=물 'D'=문 's'=표지판 'T'=나무")
    out.append("")
    out.append("// NpcDef.spriteId: sprites.h NpcSpriteId enum (0=MOM, 1=OAK, 2=BLUE, ...)")
    out.append("// NpcDef.trigger:  대화 종료 시 emit할 OwEvent (0=없음, 1=STARTER_TRIGGER)")
    out.append("struct NpcDef     { int x, y; const wchar_t* lines[4]; int spriteId = 0; int trigger = 0; };")
    out.append("struct TrainerDef { int x, y, dir, sightRange; const wchar_t* name; const wchar_t* preBattleText; int partyIds[3]; int partyLevels[3]; bool defeated; int spriteId = 11; int introSpriteId = 0; };")
    out.append("struct WarpDef    { int srcX, srcY; int destMap; int destX, destY; };")
    out.append("struct EncounterEntry { int speciesId; int minLevel, maxLevel; int weight; };")
    out.append("")
    out.append("struct MapDef {")
    out.append("    int id;")
    out.append("    int mapW, mapH;")
    out.append("    const char* name;")
    out.append("    const wchar_t* nameW;")
    out.append("    const char* tiles[72];")
    out.append("    NpcDef npcs[8]; int numNpcs;")
    out.append("    TrainerDef trainers[4]; int numTrainers;")
    out.append("    WarpDef warps[12]; int numWarps;")
    out.append("    EncounterEntry encounters[6]; int numEncounters;")
    out.append("    int northMap, southMap;")
    out.append("    int northEntryX, northEntryY;")
    out.append("    int southEntryX, southEntryY;")
    out.append("    const wchar_t* bgmFile;")
    out.append("};")
    out.append("")

    for i, (cpp_id, *_) in enumerate(MAPS):
        out.append(f"static const int {cpp_id} = {i};")
    out.append(f"static const int MAP_PLAYER_HOUSE2 = {len(MAPS)};")
    out.append(f"static const int MAP_RIVAL_HOUSE   = {len(MAPS)+1};")
    out.append("")
    out.append("inline bool isIndoorMap(int id) {")
    out.append("    return id == MAP_OAK_LAB || id == MAP_PLAYER_HOUSE")
    out.append("        || id == MAP_PLAYER_HOUSE2 || id == MAP_PEWTER_GYM")
    out.append("        || id == MAP_RIVAL_HOUSE;")
    out.append("}")
    out.append("")

    map_def_names = []
    for idx, (cpp_id, eng, kor, blk_name) in enumerate(MAPS):
        rows, w, h = load_map_png(blk_name)
        meta = load_map_json(blk_name)
        print(f"[{idx+1}/{len(MAPS)}] {eng} {w}×{h} (warps={len(meta['warps'])}, signs={len(meta['signs'])})")

        def_name = f"MAP_{idx}"
        map_def_names.append(def_name)
        out.append(f"// ─── {eng} ({w}×{h}) ─────")
        out.append(f"inline MapDef {def_name} = {{")
        out.append(f"    {cpp_id}, {w}, {h},")
        out.append(f'    "{eng}", L"{kor}",')
        out.append("    {")
        for r in rows:
            out.append(f'        "{escape_row(r)}",')
        out.append("        nullptr")
        out.append("    },")
        out.append("    {}, 0,  // npcs (런타임 처리)")
        out.append("    {}, 0,  // trainers")

        # warps
        warps = meta["warps"]
        if warps:
            out.append("    {")
            for wx, wy, dest in warps:
                out.append(f"        {{{wx}, {wy}, {map_dest(dest)}, -1, -1}},")
            out.append(f"    }}, {len(warps)},  // warps")
        else:
            out.append("    {}, 0,  // warps")

        # encounters
        encs = meta.get("encounters") or []
        if encs:
            out.append("    {")
            for enc in encs:
                sid, lo, hi, weight, name = enc
                out.append(f"        {{{sid}, {lo}, {hi}, {weight}}}, // {name}")
            out.append(f"    }}, {len(encs)},  // encounters")
        else:
            out.append("    {}, 0,  // no encounters")

        north = meta.get("north")
        south = meta.get("south")
        out.append(f"    {north if north else -1}, {south if south else -1},")
        out.append("    -1, -1, -1, -1,  // entry positions (unused)")
        out.append('    L""')
        out.append("};")
        out.append("")

    # 인덱스 → MapDef 포인터
    out.append("inline MapDef* getMap(int id) {")
    out.append("    switch(id) {")
    for i, name in enumerate(map_def_names):
        out.append(f"    case {i}: return &{name};")
    out.append("    default: return nullptr;")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append("inline char getTile(MapDef* m, int x, int y) {")
    out.append("    if (!m || y < 0 || y >= m->mapH || x < 0 || x >= m->mapW) return '#';")
    out.append("    if (!m->tiles[y]) return '#';")
    out.append("    int len = 0; while (m->tiles[y][len]) len++;")
    out.append("    if (x >= len) return ' ';")
    out.append("    return m->tiles[y][x];")
    out.append("}")
    out.append("")
    out.append("// 충돌/인카운터 헬퍼 — overworld.cpp 가 사용")
    out.append("inline bool tileWalkable(char t) {")
    out.append("    return t == ' ' || t == '.' || t == ',' || t == ';';")
    out.append("}")
    out.append("inline bool tileIsEncounter(char t) {")
    out.append("    return t == ';';")
    out.append("}")

    text = "\n".join(out) + "\n"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"\n✓ 생성 완료: {OUT}")

if __name__ == "__main__":
    generate()
