"""
pokered GFX -> 터미널 ANSI 스프라이트 변환기
출력: src/data/sprites.h
"""
import urllib.request, io, sys
from PIL import Image

BASE = "https://raw.githubusercontent.com/pret/pokered/master/gfx/pokemon/front/{}.png"
BACK = "https://raw.githubusercontent.com/pret/pokered/master/gfx/pokemon/back/{}b.png"

# 게임에 등장하는 포켓몬 (영문이름, 한글이름, ID)
MONS = [
    ("bulbasaur",  "이상해씨",  1),
    ("charmander", "파이리",    4),
    ("squirtle",   "꼬부기",    7),
    ("caterpie",   "캐터피",   10),
    ("metapod",    "메타포드", 11),
    ("weedle",     "뿔충이",   13),
    ("pidgey",     "구구",     16),
    ("rattata",    "꼬렛",     19),
    ("pikachu",    "피카츄",   25),
    ("geodude",    "꼬마돌",   74),
    ("onix",       "롱스톤",   95),
]

# 출력 크기: 14 chars wide × 9 half-block rows (= 14×18 pixels)
OUT_W = 14
OUT_H = 18  # pixels (9 half-block rows)

# GB green palette ANSI 256-color nearest
# Original GB: white=#9BBC0F, lgray=#8BAC0F, dgray=#306230, black=#0F380F
# ANSI 256: 22=dark green(#005f00) 28=#008700 34=#00af00 40=#00d700 58=#5f8700
FG_DARK  = "38;5;22"   # 진한 초록
FG_MID   = "38;5;28"   # 중간 초록
FG_LIGHT = "38;5;34"   # 연한 초록
BG_BLK   = "48;5;0"    # 검정 배경
BG_DARK  = "48;5;22"
BG_MID   = "48;5;28"
BG_LIGHT = "48;5;34"

def fetch_image(url):
    try:
        with urllib.request.urlopen(url, timeout=10) as r:
            return Image.open(io.BytesIO(r.read())).convert("RGBA")
    except Exception as e:
        print(f"  오류: {e}", file=sys.stderr)
        return None

def brightness(r, g, b):
    return 0.299*r + 0.587*g + 0.114*b

def classify(px):
    """픽셀을 4단계로 분류: -1=투명, 0=흰색, 1=밝은회색, 2=어두운회색, 3=검정"""
    r, g, b, a = px
    if a < 64:
        return -1  # 투명
    br = brightness(r, g, b)
    if br > 180: return 0   # 흰색/매우밝음
    if br > 110: return 1   # 밝은 회색
    if br > 50:  return 2   # 어두운 회색
    return 3                # 검정

# ANSI 포그라운드/배경 색상 매핑
# (top_class, bot_class) -> (char_utf8, ansi_seq)
def half_block(top, bot):
    """
    half-block 문자 선택
    top: 위 픽셀 분류 (-1,0,1,2,3)
    bot: 아래 픽셀 분류
    반환: (utf8_str) with embedded ANSI
    """
    # -1만 투명 처리 (alpha < 64). 0=흰색은 가장 밝은 초록으로 렌더링.
    top_t = (top < 0)
    bot_t = (bot < 0)

    def fg(cls):
        if cls < 0:  return BG_BLK    # transparent = black
        if cls == 0: return FG_LIGHT  # white = 가장 밝은 초록
        if cls == 1: return FG_LIGHT
        if cls == 2: return FG_MID
        return FG_DARK

    def bg(cls):
        if cls < 0:  return BG_BLK   # transparent = black
        if cls == 0: return BG_LIGHT # white = 가장 밝은 초록 배경
        if cls == 1: return BG_LIGHT
        if cls == 2: return BG_MID
        return BG_DARK

    if top_t and bot_t:
        return f"\033[{BG_BLK}m "
    elif top_t:
        # 아래만 색깔
        return f"\033[{BG_BLK};{fg(bot)}m\u2584"   # ▄ utf8
    elif bot_t:
        # 위만 색깔
        return f"\033[{BG_BLK};{fg(top)}m\u2580"   # ▀ utf8
    elif top == bot:
        # 같은 색
        return f"\033[{bg(top)}m "
    else:
        # 다른 색: ▀ fg=top, bg=bot
        return f"\033[{fg(top)};{bg(bot)}m\u2580"   # ▀

def convert_sprite(img):
    """Image -> list of 9 UTF-8 ANSI strings (각 14자 너비)"""
    # 크기 정규화: OUT_W × OUT_H 로 리사이즈
    img = img.resize((OUT_W, OUT_H), Image.NEAREST)
    rows = []
    for hy in range(OUT_H // 2):
        py0 = hy * 2
        py1 = hy * 2 + 1
        row = ""
        for x in range(OUT_W):
            t = classify(img.getpixel((x, py0)))
            b = classify(img.getpixel((x, py1)))
            row += half_block(t, b)
        row += "\033[0m"  # 리셋
        rows.append(row)
    return rows

def escape_c(s):
    """Python bytes → C string literal (hex escapes)"""
    result = ""
    for ch in s.encode("utf-8"):
        if ch == ord('"'):
            result += '\\"'
        elif ch == ord('\\'):
            result += '\\\\'
        elif 32 <= ch < 127:
            result += chr(ch)
        else:
            result += f"\\x{ch:02x}"
    return result

def make_empty_sprite():
    rows = []
    for _ in range(OUT_H // 2):
        row = "\033[0m" + "  " * OUT_W + "\033[0m"
        rows.append(row)
    return rows

# ─── 메인 ─────────────────────────────────────────────────────
lines = []
lines.append("// AUTO-GENERATED by tools/gen_sprites.py -- DO NOT EDIT")
lines.append("#pragma once")
lines.append("#include <cstring>")
lines.append("")
lines.append(f"static const int SPR_W = {OUT_W};")
lines.append(f"static const int SPR_H = {OUT_H // 2};  // half-block rows")
lines.append("")
lines.append("struct SpriteData {")
lines.append(f"    const char* rows[{OUT_H // 2}];")
lines.append("    int id;")
lines.append("};")
lines.append("")

sprite_names = []

for eng, kor, sid in MONS:
    print(f"처리 중: {kor} ({eng})...", end=" ", flush=True)
    img = fetch_image(BASE.format(eng))
    if img is None:
        print("실패, 빈 스프라이트 사용")
        rows = make_empty_sprite()
    else:
        rows = convert_sprite(img)
        print(f"완료 ({img.size[0]}×{img.size[1]}px → {OUT_W}×{OUT_H//2}half)")

    varname = f"SPR_{eng.upper()}"
    sprite_names.append((sid, varname))

    lines.append(f"// {kor} (#{sid})")
    lines.append(f"static const SpriteData {varname} = {{{{")
    for row in rows:
        lines.append(f'    "{escape_c(row)}",')
    lines.append(f"}}, {sid}}};")
    lines.append("")

# 뒷모습 (플레이어용): 스타터 + 잡을 수 있는 모든 포켓몬
lines.append("// ─── 뒷모습 (플레이어 파티) ─────────────────────────────")
BACKS = [
    ("bulbasaur",  1),
    ("charmander", 4),
    ("squirtle",   7),
    ("caterpie",   10),
    ("metapod",    11),
    ("weedle",     13),
    ("pidgey",     16),
    ("rattata",    19),
    ("pikachu",    25),
    ("geodude",    74),
    ("onix",       95),
]
for eng, sid in BACKS:
    print(f"뒷모습: {eng}...", end=" ", flush=True)
    img = fetch_image(BACK.format(eng))
    if img is None:
        print("실패")
        rows = make_empty_sprite()
    else:
        rows = convert_sprite(img)
        print("완료")
    varname = f"SPR_BACK_{eng.upper()}"
    sprite_names.append((-sid, varname))
    lines.append(f"static const SpriteData {varname} = {{{{")
    for row in rows:
        lines.append(f'    "{escape_c(row)}",')
    lines.append(f"}}, {-sid}}};")
    lines.append("")

# getter 함수
lines.append("// 앞모습 getter")
lines.append("inline const SpriteData* getSpriteFront(int id) {")
lines.append("    switch(id) {")
for sid, varname in sprite_names:
    if sid > 0:
        lines.append(f"    case {sid}: return &{varname};")
lines.append("    default: return nullptr;")
lines.append("    }")
lines.append("}")
lines.append("")
lines.append("// 뒷모습 getter")
lines.append("inline const SpriteData* getSpriteBack(int id) {")
lines.append("    switch(id) {")
for sid, varname in sprite_names:
    if sid < 0:
        lines.append(f"    case {-sid}: return &{varname};")
lines.append("    default: return nullptr;")
lines.append("    }")
lines.append("}")

output = "\n".join(lines) + "\n"
out_path = "../src/data/sprites.h"
with open(out_path, "w", encoding="utf-8") as f:
    f.write(output)
print(f"\n생성 완료: {out_path}")
