// SEMI-AUTO-GENERATED by tools/gen_maps.py
// 골격(타일/워프)은 자동 생성, NPC/대사/트리거/추가 맵(MAP_RIVAL_HOUSE 등)은 손편집 영역.
// 재생성 시 손편집된 데이터가 사라집니다 — git diff로 복원 필요.
#pragma once
#include "sprites.h"  // NPC_SPR_* enum 사용

// ─── 타일 종류 ─────────────────────────────────────────────────
// ' '  빈 땅/잔디 (이동 가능)
// '.'  길 (이동 가능)
// ';'  긴 풀 (야생 인카운터)
// '#'  벽/건물/나무 (통과 불가)
// '~'  물 (통과 불가, 비주얼)
// 'D'  문 (워프 타일)
// 's'  표지판
// 'N'  NPC 위치

// NpcDef.spriteId / TrainerDef.spriteId 는 sprites.h의 NpcSpriteId enum 인덱스.
//   0 MOM   1 OAK   2 BLUE        3 GRAMPS    4 NURSE    5 CLERK
//   6 GIRL  7 BRUNETTE   8 LITTLE_BOY  9 LITTLE_GIRL  10 FISHER
//   11 GENTLEMAN   12 POKE_BALL
// NpcDef.trigger: 대화 종료 시 emit할 이벤트
//   0 = 없음, 1 = STARTER_TRIGGER (연구소 오박사 → 스타터 선택)
struct NpcDef {
    int x, y;
    const wchar_t* lines[4];
    int spriteId = 0;       // 기본 0 = MOM
    int trigger  = 0;       // 기본 0 = 트리거 없음
};

struct TrainerDef {
    int x, y;
    int dir;
    int sightRange;
    const wchar_t* name;
    const wchar_t* preBattleText;
    int partyIds[3];
    int partyLevels[3];
    bool defeated;
    int spriteId = 11;       // OW 모양 — 기본 GENTLEMAN
    int introSpriteId = 0;   // 배틀 시작 시 풀바디 IntroSprite (0=OAK, 1=RIVAL, ...)
};

struct WarpDef {
    int srcX, srcY;
    int destMap;
    int destX, destY;
};

struct EncounterEntry {
    int speciesId;
    int minLevel, maxLevel;
    int weight;
};

struct MapDef {
    int         id;
    int         mapW, mapH;   // 실제 맵 크기 (스텝 단위)
    const char* name;
    const wchar_t* nameW;
    const char* tiles[72];   // 최대 72행 지원
    NpcDef      npcs[8];
    int         numNpcs;
    TrainerDef  trainers[4];
    int         numTrainers;
    WarpDef     warps[12];
    int         numWarps;
    EncounterEntry encounters[6];
    int         numEncounters;
    int         northMap;
    int         southMap;
    int         northEntryX, northEntryY;
    int         southEntryX, southEntryY;
    const wchar_t* bgmFile;
};

static const int MAP_PALLET = 0;
static const int MAP_ROUTE1 = 1;
static const int MAP_VIRIDIAN = 2;
static const int MAP_ROUTE2 = 3;
static const int MAP_VIR_FOREST = 4;
static const int MAP_PEWTER = 5;
static const int MAP_OAK_LAB = 6;
static const int MAP_PLAYER_HOUSE = 7;
static const int MAP_PEWTER_GYM = 8;
static const int MAP_PLAYER_HOUSE2 = 9;
static const int MAP_RIVAL_HOUSE   = 10;

// 실내 맵 ID — 맵 외곽 영역을 풀밭 대신 검정으로 렌더링
inline bool isIndoorMap(int id) {
    return id == MAP_OAK_LAB || id == MAP_PLAYER_HOUSE ||
           id == MAP_PLAYER_HOUSE2 || id == MAP_PEWTER_GYM ||
           id == MAP_RIVAL_HOUSE;
}

// ─── Pallet Town (20×18) — pokered PalletTown.blk 원본 ─────────
inline MapDef MAP_0 = {
    MAP_PALLET, 20, 18,
    "Pallet Town", L"팔레트시티",
    {
        "00010000012210000010",
        "11111111112211111111",
        "10343434343434343401",
        "10435667434356674301",
        "10889DEF34889DEF3401",
        "108GHIJK438GHIJK4301",
        "10343434343434343401",
        "10434343434343434301",
        "1034888834LMMMMN3401",
        "1043OOOG43PQQQQR4301",
        "1034SSSS34TUVWXY3401",
        "1043ZZZZ43!JIJJ@4301",
        "10343434348888888801",
        "1043434343OOOGOO8801",
        "1000$%%^88SSSS008801",
        "1000&**(88ZZZZ008801",
        "1000&**(888888888801",
        "1100&**(111111111111",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {
        // pokered PalletTown.asm 원본 위치
        {5, 5, MAP_PLAYER_HOUSE, -1, -1},
        {13, 5, MAP_RIVAL_HOUSE, -1, -1},
        {12, 11, MAP_OAK_LAB, -1, -1},
    }, 3,  // warps
    {}, 0,  // no encounters
    MAP_ROUTE1, -1,  // north/south
    10, 17, 10, 0,  // entry points
    nullptr  // bgm
};

// ─── Route 1 (20×36) ─────────────────────────────────────
inline MapDef MAP_1 = {
    MAP_ROUTE1, 20, 36,
    "Route 1", L"1번도로",
    {
        "   #     #  #     # ",
        "   #######  ####### ",
        "   #              # ",
        "   #              # ",
        "   #     #        # ",
        "   #     #        # ",
        "   #     #;;;;;;;;# ",
        "   #     #;;;;;;;;# ",
        "   #     #;;;;;;;;# ",
        "   #     #;;;;;;;;# ",
        "   #              # ",
        "   #              # ",
        "   #          ;;;;# ",
        "   ###    ####;;;;# ",
        "   #          ;;;;# ",
        "   #          ;;;;# ",
        "   #              # ",
        "   #              # ",
        "   #              # ",
        "   #              # ",
        "   #              # ",
        "   #              # ",
        "   #        ;;;;  # ",
        "   #########;;;;  # ",
        "   #        ;;;;  # ",
        "   #        ;;;;  # ",
        "   #              # ",
        "   #     s        # ",
        "   #  ;;;;    ;;;;# ",
        "   #  ;;;;    ;;;;# ",
        "   #;;;;    ;;;;  # ",
        "   #;;;;    ;;;;  # ",
        "   #######;;####### ",
        "   #     #;;#     # ",
        "   #     #;;#     # ",
        "   #     #;;#     # ",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {}, 0,  // warps
    {
        {19, 2, 4, 50},
        {16, 2, 4, 50},
    }, 2,  // encounters
    MAP_VIRIDIAN, MAP_PALLET,  // north/south
    10, 35, 10, 0,  // entry points
    nullptr  // bgm
};

// ─── Viridian City (40×36) ─────────────────────────────────────
inline MapDef MAP_2 = {
    MAP_VIRIDIAN, 40, 36,
    "Viridian City", L"상록시티",
    {
        "#####~###########   ####################",
        "#####~###########  s####################",
        "#####~###########   ####            ####",
        "#####~###########   ####            ####",
        "#####~        ~             ######  ####",
        "#####~  ########            ######  ####",
        "#####~ ##########   #       ######  ####",
        "#####~ ##########   #      s####D#  ####",
        "#####~ ##########   ####            ####",
        "#####~ ##########   #D##            ####",
        "#####~ ##########                   ####",
        "#####~ ##########                   ####",
        "#####~ ##########                   ####",
        "###### ##########   ####################",
        "       ##########   ####            ####",
        "       ##########   #D##            ####",
        "        ########            ####    ####",
        "                 s  ####    ####    ####",
        "####                        ####    ####",
        "###~                        #Ds#    ####",
        "###~                                ####",
        "###~####                            ####",
        "###~    ~             ####          ####",
        "###~    ##            ####          ####",
        "###~                  ####          ####",
        "###~    #~~~~         #Ds#          ####",
        "###~    #~~~~                       ####",
        "####    #~~~~                       ####",
        "   #                                ####",
        "   #                 s              ####",
        "   #                                ####",
        "   #################  ##################",
        "             #     #  #     #           ",
        "             #     #  #     #           ",
        "             #     #  #     #           ",
        "             #     #  #     #           ",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {
        {23, 25, -1  /*VIRIDIAN_POKECENTER*/, -1, -1},
        {29, 19, -1  /*VIRIDIAN_MART*/, -1, -1},
        {21, 15, -1  /*VIRIDIAN_SCHOOL_HOUSE*/, -1, -1},
        {21, 9, -1  /*VIRIDIAN_NICKNAME_HOUSE*/, -1, -1},
        {32, 7, -1  /*VIRIDIAN_GYM*/, -1, -1},
    }, 5,  // warps
    {}, 0,  // no encounters
    MAP_ROUTE2, MAP_ROUTE1,  // north/south
    20, 35, 20, 0,  // entry points
    nullptr  // bgm
};

// ─── Route 2 (20×36) ─────────────────────────────────────
inline MapDef MAP_3 = {
    MAP_ROUTE2, 20, 36,
    "Route 2", L"2번도로",
    {
        "########  ##########",
        "########  ##########",
        ";;;;;;;;  #         ",
        ";;;;;;;;  #         ",
        ";;;;;;;;  #         ",
        ";;;;;;;;  #         ",
        ";;;;;;;;  ~#######  ",
        ";;;;;;;;  ~######~  ",
        "          ~######~  ",
        "          ##D#####  ",
        "### #~####          ",
        "  # #      s        ",
        "  ####              ",
        "  ####              ",
        "  ####              ",
        "###D##########      ",
        "        ######      ",
        "        ######      ",
        "        ##########  ",
        "        #######D##  ",
        ";;  ;;;;######      ",
        ";;  ;;;;######      ",
        "###############~####",
        "###############     ",
        "##############      ",
        "##############      ",
        "##############      ",
        "##############      ",
        "##############      ",
        "##############      ",
        "##############      ",
        "##############      ",
        "##############      ",
        "##############      ",
        "##############      ",
        "################  ##",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {
        {12, 9, -1  /*DIGLETTS_CAVE_ROUTE_2*/, -1, -1},
        {3, 11, -1  /*VIRIDIAN_FOREST_NORTH_GATE*/, -1, -1},
        {15, 19, -1  /*ROUTE_2_TRADE_HOUSE*/, -1, -1},
        {16, 35, -1  /*ROUTE_2_GATE*/, -1, -1},
        {15, 39, -1  /*ROUTE_2_GATE*/, -1, -1},
        {3, 43, -1  /*VIRIDIAN_FOREST_SOUTH_GATE*/, -1, -1},
    }, 6,  // warps
    {
        {19, 3, 5, 50},
        {16, 3, 5, 50},
    }, 2,  // encounters
    MAP_VIR_FOREST, MAP_VIRIDIAN,  // north/south
    10, 35, 10, 0,  // entry points
    nullptr  // bgm
};

// ─── Viridian Forest (18×28) ─────────────────────────────────────
inline MapDef MAP_4 = {
    MAP_VIR_FOREST, 18, 28,
    "Viridian Forest", L"상록숲",
    {
        "#  ###############",
        "# s###        ##  ",
        "################# ",
        "               ## ",
        " ###        ##    ",
        " ###        ##    ",
        "             ##  #",
        "##########   ##  #",
        "##   ##   ##   ###",
        "##   ##   ##   ###",
        "#########  ##  ###",
        "#########  ##  ###",
        "   ##   ##   #####",
        "   ##   ##   #####",
        "#######  ##  ###  ",
        "#######  ##  ###  ",
        " ##   ##          ",
        " ##   ##          ",
        "       ##  ###   #",
        "       ##  ###   #",
        "#   ##   ######  #",
        "#   ##   ######  #",
        "##   ##  ###   ## ",
        "##   ##  ###   ## ",
        "  ##s  ######  ###",
        "  ##   ######  ###",
        "   ##  ###   ##   ",
        "   ##  ###   ##   ",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {
        {1, 0, -1  /*VIRIDIAN_FOREST_NORTH_GATE*/, -1, -1},
        {2, 0, -1  /*VIRIDIAN_FOREST_NORTH_GATE*/, -1, -1},
        {15, 47, -1  /*VIRIDIAN_FOREST_SOUTH_GATE*/, -1, -1},
        {16, 47, -1  /*VIRIDIAN_FOREST_SOUTH_GATE*/, -1, -1},
        {17, 47, -1  /*VIRIDIAN_FOREST_SOUTH_GATE*/, -1, -1},
        {18, 47, -1  /*VIRIDIAN_FOREST_SOUTH_GATE*/, -1, -1},
    }, 6,  // warps
    {
        {10, 3, 5, 55},
        {13, 3, 5, 35},
        {25, 3, 5, 5},
        {11, 4, 6, 5},
    }, 4,  // encounters
    MAP_PEWTER, MAP_ROUTE2,  // north/south
    9, 27, 9, 0,  // entry points
    nullptr  // bgm
};

// ─── Pewter City (20×18) ─────────────────────────────────────
inline MapDef MAP_5 = {
    MAP_PEWTER, 20, 18,
    "Pewter City", L"회색시티",
    {
        "                    ",
        "    ################",
        "                    ",
        "####################",
        "####      ##########",
        "###~      ##########",
        "####           #####",
        "########       #####",
        "###~      ##########",
        "###~      ~~~~~s~##D",
        "####  ~        #####",
        "####  ##       #####",
        "###~      ########  ",
        "###~      ####D###  ",
        "       #       #####",
        "       #       #####",
        "###~                ",
        "###~       s   #    ",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {
        {14, 7, -1  /*MUSEUM_1F*/, -1, -1},
        {19, 5, -1  /*MUSEUM_1F*/, -1, -1},
        {16, 17, MAP_PEWTER_GYM, -1, -1},
        {29, 13, -1  /*PEWTER_NIDORAN_HOUSE*/, -1, -1},
        {23, 17, -1  /*PEWTER_MART*/, -1, -1},
        {7, 29, -1  /*PEWTER_SPEECH_HOUSE*/, -1, -1},
        {13, 25, -1  /*PEWTER_POKECENTER*/, -1, -1},
    }, 7,  // warps
    {}, 0,  // no encounters
    -1, MAP_VIR_FOREST,  // north/south
    10, 17, 10, 0,  // entry points
    nullptr  // bgm
};

// ─── Oak's Lab (10×12) — gym tileset, quadrant별 정밀 layout ─────
// gen_oaklab_tiles.py가 OaksLab.blk + gym.bst를 디코드:
// 14 unique step variant (block의 4 quadrant마다 다른 atomic 4-tuple).
// '+'=floor(walkable), 'D'=도어. 나머지 12 char = 가구 종류별 (모두 unwalkable).
inline MapDef MAP_6 = {
    MAP_OAK_LAB, 10, 12,
    "Oak's Lab", L"오박사 연구소",
    {
        "]]]]``[[[[",   // 윗책장 (왼쪽 책장 윗부분 + 가운데 책장 윗 + 우측 책장 윗)
        "<>=_++||||",   // 책장 본체 (왼쪽 가구 + 통로 + 우측 책장)
        ":-:-++++++",   // 좌측 카운터 + 빈
        "++++++={_+",   // 빈 + 우측 카운터 위 (몬스터볼 자리!)
        "++++++:}-+",   // 빈 + 카운터 앞면
        "++++++++++",
        "[[[[++[[[[",   // 책장 윗부분 + 통로
        "||||++||||",   // 책장 본체 + 통로
        "++++++++++",   // 빈 (블루/NPC 자리)
        "++++++++++",
        "++++++++++",   // 입구 floor
        "++++??++++",   // OakLab 전용 도어 (gym tileset 모양 — 다른 맵 'D'와 분리)
        nullptr
    },
    {
        // 우측 카운터 위 (y=3, x=6,7,8) — 진짜 테이블 위에 몬스터볼 3개
        {6, 3, {L"이상해씨의 몬스터볼이다.", L"오박사: 멋대로 만지면 안 돼!", nullptr}, NPC_SPR_POKE_BALL},
        {7, 3, {L"파이리의 몬스터볼이다.",   L"오박사: 멋대로 만지면 안 돼!", nullptr}, NPC_SPR_POKE_BALL},
        {8, 3, {L"꼬부기의 몬스터볼이다.",   L"오박사: 멋대로 만지면 안 돼!", nullptr}, NPC_SPR_POKE_BALL},
        // 오박사 (책장 통로 아래쪽) — 대화 끝 → STARTER_TRIGGER
        {5, 3, {
            L"오박사: 나에겐 연구에 쓰던 세 마리의 포켓몬이 있단다.",
            L"오박사: 테이블 위 몬스터볼 안에 있어.",
            L"오박사: 자, 어떤 녀석이 마음에 드니?",
            nullptr
        }, NPC_SPR_OAK, 1},
        // 블루 (라이벌, 중앙)
        {4, 8, {
            L"블루: 야, 늦었잖아!",
            L"블루: 할아버지, 저도 한 마리 받을게요!",
            nullptr
        }, NPC_SPR_BLUE},
        // 보조원 소녀 (왼쪽)
        {1, 9, {
            L"보조원: 안녕하세요!",
            L"보조원: 오박사님은 저쪽에 계세요.",
            nullptr
        }, NPC_SPR_GIRL},
        // 과학자 (오른쪽)
        {8, 9, {
            L"과학자: 포켓몬 연구는 정말 재밌어요!",
            nullptr
        }, NPC_SPR_GENTLEMAN},
    }, 7,  // npcs
    {}, 0,  // trainers
    {
        // 도어 → 팔레트시티 (12,12) 연구소 정문 바로 아래 floor.
        // -1,-1 (southEntry 사용)면 팔레트 (10,0) = 풀숲 진입점에 떨어져 OAK_INTERCEPT 재발동됨.
        {4, 11, MAP_PALLET, 12, 12},
        {5, 11, MAP_PALLET, 12, 12},
    }, 2,  // warps
    {}, 0,  // no encounters
    -1, MAP_PALLET,  // north/south
    5, 11, 5, 10,  // entry: 정문(12,11→연구소) 진입 시 (5,10) 문 안쪽
    nullptr  // bgm
};

// ─── Player's House (8×8) ─────────────────────────────────────
inline MapDef MAP_7 = {
    MAP_PLAYER_HOUSE, 8, 8,
    "Player's House", L"주인공의 집",
    {
        "qqrsrsrs",
        "ttuvuuuw",
        "uuuuuuuu",
        "uuuuuuuu",
        "uuxyzxuu",
        "uuxABxuu",
        "uuuuuuuu",
        "uuCCuuuu",
        nullptr
    },
    {
        // Mom NPC at (5,4) — pokered 원본 위치 (RedsHouse1F.asm)
        {5, 4, {
            L"엄마: 그래. 남자애는 언젠가 집을 떠난다지.",
            L"엄마: TV에서 그러더라.",
            L"엄마: 옆집의 오박사님이 너를 찾고 계셔.",
            nullptr
        }},
    }, 1,  // npcs
    {}, 0,  // trainers
    {
        // 정문 (2,7), (3,7) → 팔레트시티 (5,6) — 플레이어 집(5,5) 바로 아래
        {2, 7, MAP_PALLET, 5, 6},
        {3, 7, MAP_PALLET, 5, 6},
        // 사다리 'w' (7,1) → 2F (7,2)
        {7, 1, MAP_PLAYER_HOUSE2, 7, 2},
    }, 3,  // warps
    {}, 0,  // no encounters
    -1, MAP_PALLET,  // north/south
    3, 7, 3, 7,  // entry: 팔레트→1F 도착시 (3,7) (정문)
    nullptr  // bgm
};

// ─── Player's Bedroom 2F (12×10) ─────────────────────────────────
// 사방에 벽(#), 좌측 상단 침대(bb), 컴퓨터(p), TV(s), 우측 상단 계단(D).
inline MapDef MAP_9 = {
    MAP_PLAYER_HOUSE2, 8, 8,
    "Player's Bedroom", L"주인공의 방",
    {
        "abcddede",
        "fghiiiij",
        "iiiiiiii",
        "iiiiiiii",
        "iiikiiii",
        "iiiliiii",
        "miiiiini",
        "oiiiiipi",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {
        // 사다리 'j' (7,1) → 1F (7,2). 사다리 밟으면 즉시 워프
        {7, 1, MAP_PLAYER_HOUSE, 7, 2},
    }, 1,  // warps
    {}, 0,  // no encounters
    -1, MAP_PLAYER_HOUSE,  // north/south
    7, 2, 7, 2,  // entry: 1F→2F 도착시 (7,2) (사다리 한 칸 아래)
    nullptr  // bgm
};

// ─── Pewter Gym (8×14) ─────────────────────────────────────
inline MapDef MAP_8 = {
    MAP_PEWTER_GYM, 8, 14,
    "Pewter Gym", L"회색시티 체육관",
    {
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "    DD  ",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {
        {4, 13, MAP_PALLET, -1, -1},
        {5, 13, MAP_PALLET, -1, -1},
    }, 2,  // warps
    {}, 0,  // no encounters
    -1, MAP_PEWTER,  // north/south
    4, 13, 4, 0,  // entry points
    nullptr  // bgm
};

// ─── Rival's House (8×8) ─────────────────────────────────────
// pokered BluesHouse 원본 — single floor (2층 없음). Daisy(블루의 누나) NPC + 책장.
// 정문 (2,7)(3,7) → 팔레트시티 (13,6).
// (7,1)은 player house 1F의 사다리 'w' 자리였으나 라이벌 집은 2층 없으므로 'q' 벽으로 변경.
inline MapDef MAP_10 = {
    MAP_RIVAL_HOUSE, 8, 8,
    "Rival's House", L"라이벌의 집",
    {
        "qqrsrsrs",
        "ttuvuuuv",   // 원작 BluesHouse (3,0) block 0x09 = 책장 → step (7,1) = 'v' (책상/책장)
        "uuuuuuuu",
        "uuxyzxuu",
        "uuxABxuu",
        "uuuuuuuu",
        "uuuuuuuu",
        "uuCCuuuu",   // 정문 — 라이벌 집도 reds_house tileset이라 'C' (RH_XC, 주인공 집과 동일)
        nullptr
    },
    {
        // Daisy (블루의 누나) — 책상 옆 (3,3)
        {3, 3, {
            L"데이지: 안녕! 동생은 할아버지 연구소에 갔단다.",
            L"데이지: 너도 곧 모험을 떠나는 거지?",
            L"데이지: 포켓몬은 살아있는 친구야. 잘 돌봐줘!",
            nullptr
        }, NPC_SPR_BRUNETTE},
    }, 1,  // npcs
    {}, 0,  // trainers
    {
        {2, 7, MAP_PALLET, 13, 6},
        {3, 7, MAP_PALLET, 13, 6},
    }, 2,  // warps
    {}, 0,  // no encounters
    -1, MAP_PALLET,  // north/south
    3, 7, 3, 7,
    nullptr
};

// ─── 전체 맵 배열 ────────────────────────────────────────────
// ALL_MAPS의 인덱스 = MAP_xxx 상수값.
// (MAP_PLAYER_HOUSE=7, MAP_PEWTER_GYM=8, MAP_PLAYER_HOUSE2=9, MAP_RIVAL_HOUSE=10)
inline MapDef* ALL_MAPS[] = {
    &MAP_0,
    &MAP_1,
    &MAP_2,
    &MAP_3,
    &MAP_4,
    &MAP_5,
    &MAP_6,
    &MAP_7,
    &MAP_8,
    &MAP_9,
    &MAP_10,
};
inline constexpr int NUM_MAPS = 11;

inline MapDef* getMap(int id) {
    if (id >= 0 && id < NUM_MAPS) return ALL_MAPS[id];
    return nullptr;
}

// walkable: 길/잔디/floor만. 가구/벽/워프 char(t,v,w,x,y,z,A,B,C,j,#)는 unwalkable
// → 워프 char는 tryMove의 !walkable 분기에서 워프 트리거.
//   '#' = TILE_WALL (벽), 맵 경계 밖에서도 '#' 반환됨 → unwalkable이어야 경계 차단.
inline bool tileWalkable(char t) {
    return t == ' ' || t == '!' || t == '$' || t == '%' || t == '(' || t == '+' || t == '0' || t == '1' || t == '2' || t == '3' || t == '4' || t == '8' || t == ';' || t == '@' || t == 'H' || t == 'I' || t == 'J' || t == 'K' || t == 'S' || t == 'Z' || t == '^' || t == 'i' || t == 'u';
}
inline bool tileIsEncounter(char t) {
    return t == '2' || t == ';';
}
inline char getTile(const MapDef* m, int x, int y) {
    if (!m || x < 0 || x >= m->mapW || y < 0 || y >= m->mapH) return '#';
    if (!m->tiles[y]) return '#';
    int len = 0; while (m->tiles[y][len]) len++;
    if (x >= len) return ' ';
    return m->tiles[y][x];
}

inline bool tileIsDoor(char t) {
    return t == '!' || t == '#' || t == '(' || t == '1' || t == '@' || t == 'A' || t == 'B' || t == 'H' || t == 'I' || t == 'J' || t == 'K' || t == '^' || t == 'w';
}
