// AUTO-GENERATED by tools/gen_maps.py -- DO NOT EDIT
// pret/pokered 원본 맵 데이터 기반 (블록 좌표 → 스텝 좌표 변환)
#pragma once

// ─── 타일 종류 ─────────────────────────────────────────────────
// ' '  빈 땅/잔디 (이동 가능)
// '.'  길 (이동 가능)
// ';'  긴 풀 (야생 인카운터)
// '#'  벽/건물/나무 (통과 불가)
// '~'  물 (통과 불가, 비주얼)
// 'D'  문 (워프 타일)
// 's'  표지판
// 'N'  NPC 위치

struct NpcDef {
    int x, y;
    const wchar_t* lines[4];
};

struct TrainerDef {
    int x, y;
    int dir;
    int sightRange;
    const wchar_t* name;
    const wchar_t* preBattleText;
    int partyIds[3];
    int partyLevels[3];
    bool defeated;
};

struct WarpDef {
    int srcX, srcY;
    int destMap;
    int destX, destY;
};

struct EncounterEntry {
    int speciesId;
    int minLevel, maxLevel;
    int weight;
};

struct MapDef {
    int         id;
    int         mapW, mapH;   // 실제 맵 크기 (스텝 단위)
    const char* name;
    const wchar_t* nameW;
    const char* tiles[72];   // 최대 72행 지원
    NpcDef      npcs[8];
    int         numNpcs;
    TrainerDef  trainers[4];
    int         numTrainers;
    WarpDef     warps[12];
    int         numWarps;
    EncounterEntry encounters[6];
    int         numEncounters;
    int         northMap;
    int         southMap;
    int         northEntryX, northEntryY;
    int         southEntryX, southEntryY;
    const wchar_t* bgmFile;
};

static const int MAP_PALLET = 0;
static const int MAP_ROUTE1 = 1;
static const int MAP_VIRIDIAN = 2;
static const int MAP_ROUTE2 = 3;
static const int MAP_VIR_FOREST = 4;
static const int MAP_PEWTER = 5;
static const int MAP_OAK_LAB = 6;
static const int MAP_PLAYER_HOUSE = 7;
static const int MAP_PEWTER_GYM = 8;
static const int MAP_PLAYER_HOUSE2 = 9;
static const int MAP_RIVAL_HOUSE   = 10;

// 실내 맵 ID — 맵 외곽 영역을 풀밭 대신 검정으로 렌더링
inline bool isIndoorMap(int id) {
    return id == MAP_OAK_LAB || id == MAP_PLAYER_HOUSE ||
           id == MAP_PLAYER_HOUSE2 || id == MAP_PEWTER_GYM ||
           id == MAP_RIVAL_HOUSE;
}

// ─── Pallet Town (20×18) — pokered PalletTown.blk 원본 ─────────
inline MapDef MAP_0 = {
    MAP_PALLET, 20, 18,
    "Pallet Town", L"팔레트시티",
    {
        "00010000012210000010",
        "11111111112211111111",
        "10343434343434343401",
        "10435667434356674301",
        "10889DEF34889DEF3401",
        "108GHIJK438GHIJK4301",
        "10343434343434343401",
        "10434343434343434301",
        "1034888834LMMMMN3401",
        "1043OOOG43PQQQQR4301",
        "1034SSSS34TUVWXY3401",
        "1043ZZZZ43!JIJJ@4301",
        "10343434348888888801",
        "1043434343OOOGOO8801",
        "1000$%%^88SSSS008801",
        "1000&**(88ZZZZ008801",
        "1000&**(888888888801",
        "1100&**(111111111111",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {
        // pokered PalletTown.asm 원본 위치
        {5, 5, MAP_PLAYER_HOUSE, -1, -1},
        {13, 5, MAP_RIVAL_HOUSE, -1, -1},
        {12, 11, MAP_OAK_LAB, -1, -1},
    }, 3,  // warps
    {}, 0,  // no encounters
    MAP_ROUTE1, -1,  // north/south
    10, 17, 10, 0,  // entry points
    nullptr  // bgm
};

// ─── Route 1 (20×36) ─────────────────────────────────────
inline MapDef MAP_1 = {
    MAP_ROUTE1, 20, 36,
    "Route 1", L"1번도로",
    {
        "   #     #  #     # ",
        "   #######  ####### ",
        "   #              # ",
        "   #              # ",
        "   #     #        # ",
        "   #     #        # ",
        "   #     #;;;;;;;;# ",
        "   #     #;;;;;;;;# ",
        "   #     #;;;;;;;;# ",
        "   #     #;;;;;;;;# ",
        "   #              # ",
        "   #              # ",
        "   #          ;;;;# ",
        "   ###    ####;;;;# ",
        "   #          ;;;;# ",
        "   #          ;;;;# ",
        "   #              # ",
        "   #              # ",
        "   #              # ",
        "   #              # ",
        "   #              # ",
        "   #              # ",
        "   #        ;;;;  # ",
        "   #########;;;;  # ",
        "   #        ;;;;  # ",
        "   #        ;;;;  # ",
        "   #              # ",
        "   #     s        # ",
        "   #  ;;;;    ;;;;# ",
        "   #  ;;;;    ;;;;# ",
        "   #;;;;    ;;;;  # ",
        "   #;;;;    ;;;;  # ",
        "   #######;;####### ",
        "   #     #;;#     # ",
        "   #     #;;#     # ",
        "   #     #;;#     # ",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {}, 0,  // warps
    {
        {19, 2, 4, 50},
        {16, 2, 4, 50},
    }, 2,  // encounters
    MAP_VIRIDIAN, MAP_PALLET,  // north/south
    10, 35, 10, 0,  // entry points
    nullptr  // bgm
};

// ─── Viridian City (40×36) ─────────────────────────────────────
inline MapDef MAP_2 = {
    MAP_VIRIDIAN, 40, 36,
    "Viridian City", L"상록시티",
    {
        "#####~###########   ####################",
        "#####~###########  s####################",
        "#####~###########   ####            ####",
        "#####~###########   ####            ####",
        "#####~        ~             ######  ####",
        "#####~  ########            ######  ####",
        "#####~ ##########   #       ######  ####",
        "#####~ ##########   #      s####D#  ####",
        "#####~ ##########   ####            ####",
        "#####~ ##########   #D##            ####",
        "#####~ ##########                   ####",
        "#####~ ##########                   ####",
        "#####~ ##########                   ####",
        "###### ##########   ####################",
        "       ##########   ####            ####",
        "       ##########   #D##            ####",
        "        ########            ####    ####",
        "                 s  ####    ####    ####",
        "####                        ####    ####",
        "###~                        #Ds#    ####",
        "###~                                ####",
        "###~####                            ####",
        "###~    ~             ####          ####",
        "###~    ##            ####          ####",
        "###~                  ####          ####",
        "###~    #~~~~         #Ds#          ####",
        "###~    #~~~~                       ####",
        "####    #~~~~                       ####",
        "   #                                ####",
        "   #                 s              ####",
        "   #                                ####",
        "   #################  ##################",
        "             #     #  #     #           ",
        "             #     #  #     #           ",
        "             #     #  #     #           ",
        "             #     #  #     #           ",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {
        {23, 25, -1  /*VIRIDIAN_POKECENTER*/, -1, -1},
        {29, 19, -1  /*VIRIDIAN_MART*/, -1, -1},
        {21, 15, -1  /*VIRIDIAN_SCHOOL_HOUSE*/, -1, -1},
        {21, 9, -1  /*VIRIDIAN_NICKNAME_HOUSE*/, -1, -1},
        {32, 7, -1  /*VIRIDIAN_GYM*/, -1, -1},
    }, 5,  // warps
    {}, 0,  // no encounters
    MAP_ROUTE2, MAP_ROUTE1,  // north/south
    20, 35, 20, 0,  // entry points
    nullptr  // bgm
};

// ─── Route 2 (20×36) ─────────────────────────────────────
inline MapDef MAP_3 = {
    MAP_ROUTE2, 20, 36,
    "Route 2", L"2번도로",
    {
        "########  ##########",
        "########  ##########",
        ";;;;;;;;  #         ",
        ";;;;;;;;  #         ",
        ";;;;;;;;  #         ",
        ";;;;;;;;  #         ",
        ";;;;;;;;  ~#######  ",
        ";;;;;;;;  ~######~  ",
        "          ~######~  ",
        "          ##D#####  ",
        "### #~####          ",
        "  # #      s        ",
        "  ####              ",
        "  ####              ",
        "  ####              ",
        "###D##########      ",
        "        ######      ",
        "        ######      ",
        "        ##########  ",
        "        #######D##  ",
        ";;  ;;;;######      ",
        ";;  ;;;;######      ",
        "###############~####",
        "###############     ",
        "##############      ",
        "##############      ",
        "##############      ",
        "##############      ",
        "##############      ",
        "##############      ",
        "##############      ",
        "##############      ",
        "##############      ",
        "##############      ",
        "##############      ",
        "################  ##",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {
        {12, 9, -1  /*DIGLETTS_CAVE_ROUTE_2*/, -1, -1},
        {3, 11, -1  /*VIRIDIAN_FOREST_NORTH_GATE*/, -1, -1},
        {15, 19, -1  /*ROUTE_2_TRADE_HOUSE*/, -1, -1},
        {16, 35, -1  /*ROUTE_2_GATE*/, -1, -1},
        {15, 39, -1  /*ROUTE_2_GATE*/, -1, -1},
        {3, 43, -1  /*VIRIDIAN_FOREST_SOUTH_GATE*/, -1, -1},
    }, 6,  // warps
    {
        {19, 3, 5, 50},
        {16, 3, 5, 50},
    }, 2,  // encounters
    MAP_VIR_FOREST, MAP_VIRIDIAN,  // north/south
    10, 35, 10, 0,  // entry points
    nullptr  // bgm
};

// ─── Viridian Forest (18×28) ─────────────────────────────────────
inline MapDef MAP_4 = {
    MAP_VIR_FOREST, 18, 28,
    "Viridian Forest", L"상록숲",
    {
        "#  ###############",
        "# s###        ##  ",
        "################# ",
        "               ## ",
        " ###        ##    ",
        " ###        ##    ",
        "             ##  #",
        "##########   ##  #",
        "##   ##   ##   ###",
        "##   ##   ##   ###",
        "#########  ##  ###",
        "#########  ##  ###",
        "   ##   ##   #####",
        "   ##   ##   #####",
        "#######  ##  ###  ",
        "#######  ##  ###  ",
        " ##   ##          ",
        " ##   ##          ",
        "       ##  ###   #",
        "       ##  ###   #",
        "#   ##   ######  #",
        "#   ##   ######  #",
        "##   ##  ###   ## ",
        "##   ##  ###   ## ",
        "  ##s  ######  ###",
        "  ##   ######  ###",
        "   ##  ###   ##   ",
        "   ##  ###   ##   ",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {
        {1, 0, -1  /*VIRIDIAN_FOREST_NORTH_GATE*/, -1, -1},
        {2, 0, -1  /*VIRIDIAN_FOREST_NORTH_GATE*/, -1, -1},
        {15, 47, -1  /*VIRIDIAN_FOREST_SOUTH_GATE*/, -1, -1},
        {16, 47, -1  /*VIRIDIAN_FOREST_SOUTH_GATE*/, -1, -1},
        {17, 47, -1  /*VIRIDIAN_FOREST_SOUTH_GATE*/, -1, -1},
        {18, 47, -1  /*VIRIDIAN_FOREST_SOUTH_GATE*/, -1, -1},
    }, 6,  // warps
    {
        {10, 3, 5, 55},
        {13, 3, 5, 35},
        {25, 3, 5, 5},
        {11, 4, 6, 5},
    }, 4,  // encounters
    MAP_PEWTER, MAP_ROUTE2,  // north/south
    9, 27, 9, 0,  // entry points
    nullptr  // bgm
};

// ─── Pewter City (20×18) ─────────────────────────────────────
inline MapDef MAP_5 = {
    MAP_PEWTER, 20, 18,
    "Pewter City", L"회색시티",
    {
        "                    ",
        "    ################",
        "                    ",
        "####################",
        "####      ##########",
        "###~      ##########",
        "####           #####",
        "########       #####",
        "###~      ##########",
        "###~      ~~~~~s~##D",
        "####  ~        #####",
        "####  ##       #####",
        "###~      ########  ",
        "###~      ####D###  ",
        "       #       #####",
        "       #       #####",
        "###~                ",
        "###~       s   #    ",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {
        {14, 7, -1  /*MUSEUM_1F*/, -1, -1},
        {19, 5, -1  /*MUSEUM_1F*/, -1, -1},
        {16, 17, MAP_PEWTER_GYM, -1, -1},
        {29, 13, -1  /*PEWTER_NIDORAN_HOUSE*/, -1, -1},
        {23, 17, -1  /*PEWTER_MART*/, -1, -1},
        {7, 29, -1  /*PEWTER_SPEECH_HOUSE*/, -1, -1},
        {13, 25, -1  /*PEWTER_POKECENTER*/, -1, -1},
    }, 7,  // warps
    {}, 0,  // no encounters
    -1, MAP_VIR_FOREST,  // north/south
    10, 17, 10, 0,  // entry points
    nullptr  // bgm
};

// ─── Oak's Lab (10×12) ─────────────────────────────────────
inline MapDef MAP_6 = {
    MAP_OAK_LAB, 10, 12,
    "Oak's Lab", L"오박사 연구소",
    {
        "##########",
        "##########",
        "####  ####",
        "####  ####",
        "      ####",
        "      ####",
        "####  ####",
        "####  ####",
        "          ",
        "          ",
        "          ",
        "    DD    ",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {
        {4, 11, MAP_PALLET, -1, -1},
        {5, 11, MAP_PALLET, -1, -1},
    }, 2,  // warps
    {}, 0,  // no encounters
    -1, MAP_PALLET,  // north/south
    5, 11, 5, 0,  // entry points
    nullptr  // bgm
};

// ─── Player's House (8×8) ─────────────────────────────────────
inline MapDef MAP_7 = {
    MAP_PLAYER_HOUSE, 8, 8,
    "Player's House", L"주인공의 집",
    {
        "qqrsrsrs",
        "ttuvuuuw",
        "uuuuuuuu",
        "uuuuuuuu",
        "uuxyzxuu",
        "uuxABxuu",
        "uuuuuuuu",
        "uuCCuuuu",
        nullptr
    },
    {
        // Mom NPC at (5,4) — pokered 원본 위치 (RedsHouse1F.asm)
        {5, 4, {
            L"엄마: 그래. 남자애는 언젠가 집을 떠난다지.",
            L"엄마: TV에서 그러더라.",
            L"엄마: 옆집의 오박사님이 너를 찾고 계셔.",
            nullptr
        }},
    }, 1,  // npcs
    {}, 0,  // trainers
    {
        // 정문 (2,7), (3,7) → 팔레트시티 (5,6) — 플레이어 집(5,5) 바로 아래
        {2, 7, MAP_PALLET, 5, 6},
        {3, 7, MAP_PALLET, 5, 6},
        // 사다리 'w' (7,1) → 2F (7,2)
        {7, 1, MAP_PLAYER_HOUSE2, 7, 2},
    }, 3,  // warps
    {}, 0,  // no encounters
    -1, MAP_PALLET,  // north/south
    3, 7, 3, 7,  // entry: 팔레트→1F 도착시 (3,7) (정문)
    nullptr  // bgm
};

// ─── Player's Bedroom 2F (12×10) ─────────────────────────────────
// 사방에 벽(#), 좌측 상단 침대(bb), 컴퓨터(p), TV(s), 우측 상단 계단(D).
inline MapDef MAP_9 = {
    MAP_PLAYER_HOUSE2, 8, 8,
    "Player's Bedroom", L"주인공의 방",
    {
        "abcddede",
        "fghiiiij",
        "iiiiiiii",
        "iiiiiiii",
        "iiikiiii",
        "iiiliiii",
        "miiiiini",
        "oiiiiipi",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {
        // 사다리 'j' (7,1) → 1F (7,2). 사다리 밟으면 즉시 워프
        {7, 1, MAP_PLAYER_HOUSE, 7, 2},
    }, 1,  // warps
    {}, 0,  // no encounters
    -1, MAP_PLAYER_HOUSE,  // north/south
    7, 2, 7, 2,  // entry: 1F→2F 도착시 (7,2) (사다리 한 칸 아래)
    nullptr  // bgm
};

// ─── Pewter Gym (8×14) ─────────────────────────────────────
inline MapDef MAP_8 = {
    MAP_PEWTER_GYM, 8, 14,
    "Pewter Gym", L"회색시티 체육관",
    {
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "        ",
        "    DD  ",
        nullptr
    },
    {}, 0,  // npcs
    {}, 0,  // trainers
    {
        {4, 13, MAP_PALLET, -1, -1},
        {5, 13, MAP_PALLET, -1, -1},
    }, 2,  // warps
    {}, 0,  // no encounters
    -1, MAP_PEWTER,  // north/south
    4, 13, 4, 0,  // entry points
    nullptr  // bgm
};

// ─── 전체 맵 배열 ────────────────────────────────────────────
// ALL_MAPS의 인덱스 = MAP_xxx 상수값. (MAP_PLAYER_HOUSE=7, MAP_PEWTER_GYM=8, MAP_PLAYER_HOUSE2=9)
inline MapDef* ALL_MAPS[] = {
    &MAP_0,
    &MAP_1,
    &MAP_2,
    &MAP_3,
    &MAP_4,
    &MAP_5,
    &MAP_6,
    &MAP_7,
    &MAP_8,
    &MAP_9,
};
inline constexpr int NUM_MAPS = 10;

inline MapDef* getMap(int id) {
    if (id >= 0 && id < NUM_MAPS) return ALL_MAPS[id];
    return nullptr;
}

inline bool tileWalkable(char t) {
    // 야외 야생: ' '/.,/;
    // 실내 floor: 'i'(R2F) 'u'(R1F) 'j' 'w' (사다리)
    // PalletTown: '0' '1' '3' '4' (잔디/길/floor patterns)
    return t == ' ' || t == '.' || t == ',' || t == ';'
        || t == 'i' || t == 'u' || t == 'j' || t == 'w'
        || t == '0' || t == '1' || t == '3' || t == '4';
}
inline bool tileIsEncounter(char t) { return t == ';'; }

inline char getTile(const MapDef* m, int x, int y) {
    if (!m || x < 0 || x >= m->mapW || y < 0 || y >= m->mapH) return '#';
    if (!m->tiles[y]) return '#';
    int len = 0; while (m->tiles[y][len]) len++;
    if (x >= len) return ' ';
    return m->tiles[y][x];
}
