// AUTO-GENERATED by tools/gen_tiles.py -- DO NOT EDIT
// 포켓몬 레드 실제 타일셋 스프라이트 기반
#pragma once
#include <cstring>

// 각 타일: 2글자 너비 × 2행 (half-block ANSI, 각 행=4픽셀)
static const int TILE_COLS = 2;  // 터미널 칸 수 (가로, 각 칸=2chars)
static const int TILE_ROWS = 2;  // 터미널 행 수 (세로)

struct TileArt {
    const char* rows[2];  // ANSI UTF-8 문자열 (각 4chars 너비)
    char mapChar;
};

// 빈 땅 (기본 잔디) (맵 문자: ' ')
static const TileArt TILE_GROUND = {{
    "\x1b[48;5;106m  \x1b[0m\x1b[48;5;106m  \x1b[0m",
    "\x1b[48;5;106m  \x1b[0m\x1b[48;5;106m  \x1b[0m",
}, ' '};

// 길 ($10) (맵 문자: '.')
static const TileArt TILE_PATH = {{
    "\x1b[48;5;179m  \x1b[0m\x1b[48;5;136m  \x1b[0m",
    "\x1b[48;5;179m  \x1b[0m\x1b[48;5;136m  \x1b[0m",
}, '.'};

// 짧은 풀 ($03) (맵 문자: ',')
static const TileArt TILE_GRASS = {{
    "\x1b[48;5;106;38;5;70m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m\x1b[48;5;70m  \x1b[0m",
    "\x1b[48;5;70m  \x1b[0m\x1b[48;5;70m  \x1b[0m",
}, ','};

// 긴 풀 ($52, 야생 인카운터) (맵 문자: ';')
static const TileArt TILE_TALLGRASS = {{
    "\x1b[48;5;70;38;5;28m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m\x1b[48;5;28;38;5;22m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m",
    "\x1b[48;5;28m  \x1b[0m\x1b[48;5;28m  \x1b[0m",
}, ';'};

// 건물 벽 ($02) (맵 문자: '#')
static const TileArt TILE_WALL = {{
    "\x1b[48;5;240;38;5;232m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m\x1b[48;5;250m  \x1b[0m",
    "\x1b[48;5;237;38;5;232m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m\x1b[48;5;240;38;5;237m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m",
}, '#'};

// 건물 벽 (내부용) (맵 문자: 'H')
static const TileArt TILE_HOUSE = {{
    "\x1b[48;5;240;38;5;232m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m\x1b[48;5;250m  \x1b[0m",
    "\x1b[48;5;237;38;5;232m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m\x1b[48;5;240;38;5;237m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m",
}, 'H'};

// 나무 ($32) (맵 문자: 'T')
static const TileArt TILE_TREE = {{
    "\x1b[48;5;0m  \x1b[0m\x1b[48;5;0m  \x1b[0m",
    "\x1b[48;5;0m  \x1b[0m\x1b[48;5;0;38;5;0m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m",
}, 'T'};

// 물 ($06) (맵 문자: '~')
static const TileArt TILE_WATER = {{
    "\x1b[48;5;75;38;5;33m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m\x1b[48;5;33;38;5;27m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m",
    "\x1b[48;5;27m  \x1b[0m\x1b[48;5;27m  \x1b[0m",
}, '~'};

// 문 ($14) (맵 문자: 'D')
static const TileArt TILE_DOOR = {{
    "\x1b[48;5;248m  \x1b[0m\x1b[48;5;252m  \x1b[0m",
    "\x1b[48;5;248;38;5;252m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m\x1b[48;5;252;38;5;248m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m",
}, 'D'};

// 연구소 문 (맵 문자: 'L')
static const TileArt TILE_LABDOOR = {{
    "\x1b[48;5;248m  \x1b[0m\x1b[48;5;252m  \x1b[0m",
    "\x1b[48;5;248;38;5;252m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m\x1b[48;5;252;38;5;248m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m",
}, 'L'};

// 포켓몬센터 문 (맵 문자: 'C')
static const TileArt TILE_CENTER = {{
    "\x1b[48;5;248m  \x1b[0m\x1b[48;5;252m  \x1b[0m",
    "\x1b[48;5;248;38;5;252m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m\x1b[48;5;252;38;5;248m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m",
}, 'C'};

// 체육관 문 (맵 문자: 'G')
static const TileArt TILE_GYM = {{
    "\x1b[48;5;248m  \x1b[0m\x1b[48;5;252m  \x1b[0m",
    "\x1b[48;5;248;38;5;252m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m\x1b[48;5;252;38;5;248m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m",
}, 'G'};

// 마트 문 (맵 문자: 'M')
static const TileArt TILE_MART = {{
    "\x1b[48;5;248m  \x1b[0m\x1b[48;5;252m  \x1b[0m",
    "\x1b[48;5;248;38;5;252m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m\x1b[48;5;252;38;5;248m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m",
}, 'M'};

// 표지판 (맵 문자: 's')
static const TileArt TILE_SIGN = {{
    "\x1b[48;5;248;38;5;252m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m\x1b[48;5;248;38;5;255m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m",
    "\x1b[48;5;248;38;5;255m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m\x1b[48;5;248;38;5;252m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m",
}, 's'};

// 브록/특수 (맵 문자: 'B')
static const TileArt TILE_BLOCK = {{
    "\x1b[48;5;240;38;5;232m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m\x1b[48;5;250m  \x1b[0m",
    "\x1b[48;5;237;38;5;232m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m\x1b[48;5;240;38;5;237m\xc3\xa2\xc2\x96\xc2\x84\xc3\xa2\xc2\x96\xc2\x84\x1b[0m",
}, 'B'};

// 포켓볼 테이블 (맵 문자: 'P')
static const TileArt TILE_TABLE = {{
    "\x1b[48;5;255m  \x1b[0m\x1b[48;5;255m  \x1b[0m",
    "\x1b[48;5;255m  \x1b[0m\x1b[48;5;255m  \x1b[0m",
}, 'P'};

// NPC 위치 (런타임 처리) (맵 문자: 'N')
static const TileArt TILE_NPC = {{
    "\x1b[48;5;106m  \x1b[0m\x1b[48;5;106m  \x1b[0m",
    "\x1b[48;5;106m  \x1b[0m\x1b[48;5;106m  \x1b[0m",
}, 'N'};

// 맵 문자 → 타일 아트 getter
inline const TileArt* getTileArt(char c) {
    switch(c) {
    case ' ': return &TILE_GROUND;
    case '.': return &TILE_PATH;
    case ',': return &TILE_GRASS;
    case ';': return &TILE_TALLGRASS;
    case '#': return &TILE_WALL;
    case 'H': return &TILE_HOUSE;
    case 'T': return &TILE_TREE;
    case '~': return &TILE_WATER;
    case 'D': return &TILE_DOOR;
    case 'L': return &TILE_LABDOOR;
    case 'C': return &TILE_CENTER;
    case 'G': return &TILE_GYM;
    case 'M': return &TILE_MART;
    case 's': return &TILE_SIGN;
    case 'B': return &TILE_BLOCK;
    case 'P': return &TILE_TABLE;
    case 'N': return &TILE_NPC;
    default: return &TILE_GROUND;
    }
}
